# Generated by Django 4.2 on 2023-05-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('img', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='manager',
            name='contact',
            field=models.CharField(max_length=12),
        ),
    ]
