# Generated by Django 4.2 on 2023-05-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_product_alter_client_contact_alter_manager_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
