# Generated by Django 4.2 on 2023-05-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
