# Generated by Django 4.2 on 2023-05-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_delete_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin',
            field=models.CharField(default=12, max_length=3),
            preserve_default=False,
        ),
    ]
