# Generated by Django 4.2.1 on 2023-05-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_client_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='admin',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
