# Generated by Django 4.2 on 2023-06-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='saldo',
            field=models.BigIntegerField(default=900),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
