# Generated by Django 4.2 on 2023-06-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_client_saldo_alter_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
