# Generated by Django 4.2.1 on 2024-09-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_client_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='saldo',
            field=models.PositiveSmallIntegerField(default=1757),
        ),
    ]
